/*
 * Created on Oct 5, 2004
 *
 * To change the template for this generated file go to
 * Window&gt;Preferences&gt;Java&gt;Code Generation&gt;Code and Comments
 */

package strangebrew;

/**
 * @author aavis
 *
 * To change the template for this generated type comment go to
 * Window&gt;Preferences&gt;Java&gt;Code Generation&gt;Code and Comments
 */

import strangebrew.ui.core.*;
import strangebrew.ui.swt.*;

import org.xml.sax.*;
import org.xml.sax.helpers.DefaultHandler;

import java.io.*;

import javax.xml.parsers.SAXParserFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.parsers.SAXParser;

public class TestUI {

	public static void main(String[] args) {
		Recipe myRecipe = new Recipe();

		if (args.length != 1) {
			System.err.println("Usage: filename or --gui");
			System.exit(1);
		} else if (args[0].equals("--gui")) {
			View view = new SWTMainView();
			view.init();
			MainController controller = new MainController(view);
			controller.execute();
		} else {
			// this is copied from the ImportXml main method
			// import an xml file, and write a bunch of stuff about it
			// Dont't know how to get the recipe returned from this thing, though
			
			// Use an instance of the ImportXml as the SAX event handler
			DefaultHandler handler = new ImportXml();

			// Use the default (non-validating) parser
			SAXParserFactory factory = SAXParserFactory.newInstance();
			try {

				// Parse the input
				SAXParser saxParser = factory.newSAXParser();
				saxParser.parse(new File(args[0]), handler);			

			} catch (SAXParseException spe) {
				// Error generated by the parser
				System.out.println("\n** Parsing error" + ", line "
						+ spe.getLineNumber() + ", uri " + spe.getSystemId());
				System.out.println("   " + spe.getMessage());

				// Use the contained exception, if any
				Exception x = spe;
				if (spe.getException() != null)
					x = spe.getException();
				x.printStackTrace();

			} catch (SAXException sxe) {
				// Error generated by this application
				// (or a parser-initialization error)
				Exception x = sxe;
				if (sxe.getException() != null)
					x = sxe.getException();
				x.printStackTrace();

			} catch (ParserConfigurationException pce) {
				// Parser with specified options can't be built
				pce.printStackTrace();

			} catch (IOException ioe) {
				// I/O error
				ioe.printStackTrace();
			}
		}
		
		myRecipe.testRecipe();		

}
	

}
