

    // This file was generated by build.xml, do not edit!
	package ca.strangebrew;
	public class SBVersion {
		/** JabaDex major release version */
		public final static String VERSION =
			2 + "." + 1 + "." + 0;
		public final static String BUILDDATE = "August 30, 2014";
		public final static String BUILDNUMBER = "283";
	}
	