/**
 *    Filename: Product.java
 *     Version: 0.9.0
 * Description: Product
 *     License: GPLv2
 *        Date: 2017-01-14
 *
 * Location for product information.
 *
 * Copyright (c) 2017 Dallas Fletchall
 * @author Dallas Fletchall
 */
package com.homebrewware;

import java.io.File;
import java.io.UnsupportedEncodingException;

import java.net.URLDecoder;

import generated.Build;

public class Product
{
    public static enum Path {
        ROOT,
        DATA,
        HELP,
        RECIPE,
        IMAGES,
        RESOURCES,
    }

    public static String getName() {
        return Build.NAME;
    }

    public static String getAppPath(Product.Path dir) {

        if(Product.appRoot.equals(Product.emptyPath)) {
            Product.setAppPaths();
        }

        switch(dir) {

            case ROOT:
                return appRoot;
            case DATA:
                return dataDir;
            case IMAGES:
                return imagesDir;
            case RECIPE:
                return recipesDir;
            case HELP:
                return helpDir;
            case RESOURCES:
                return resourceDir;
            default:
                /**
                 * No good way to handle this, previous implementation
                 * allowed the default case to return the appRoot
                 */
                System.err.println("Unknown Directory: " + dir);
                return appRoot;
        }
    }

    /**
     * Build class is generated by ANT, and should only be referenced
     * in this file. This will allow for changes in the future without
     * significant maintenance.
     */
    public static String getVersion() {
        return Build.Version.MAJOR + "." + Build.Version.MINOR + "." + Build.Version.REV;
    }

    public static String getBuildDate() {
        return Build.DATE;
    }

    public static String getBuildNumber() {
        return Build.NUMBER;
    }

    private static String appRoot = "";
    private static String dataDir = "";
    private static String emptyPath = "";
    private static String helpDir = "";
    private static String imagesDir = "";
    private static String recipesDir = "";
    private static String resourceDir = "";

    private static void setAppPaths() {

        /**
         * The method of getting the appRoot is not valid when called
         * inside a constructor, so just call a single time.
         */
        try {
            String jpath = new File(StringUtils.class.getProtectionDomain().getCodeSource().getLocation().getPath()).getParentFile().getPath();
		    Product.appRoot = URLDecoder.decode(jpath, "UTF-8");
        } catch(UnsupportedEncodingException e) {
            System.err.println("Unable to determine application path");
        }

        String separator = System.getProperty("file.separator");

        resourceDir = appRoot + separator + Build.Dir.RESOURCES;
        imagesDir = resourceDir + separator + Build.Dir.IMAGES;
        dataDir = resourceDir + separator + Build.Dir.DATA;
        recipesDir = resourceDir + separator + Build.Dir.RECIPES;

        helpDir = "file://" + appRoot + separator + Build.Dir.HELP;
        }
}
