
// This file was generated by build.xml, do not edit!
package com.homebrewware;
public class Product {

    public final static String SOURCE_DIR = "src";
    public final static String BINARY_DIR = "bin";
    public final static String RECIPE_DIR = "recipes";
    public final static String HELP_DIR = "help";
    public final static String DOCUMENTATION_DIR = "doc";
}
        